### ISSUE TITLE
Request: Language as parameter

### ISSUE THREAD

**Issue by quack3d** [biofects/Google-Home-Messages#4]
I would like to have my Google Home control my Alexa device from my Home Automation system. Then I can click a button to make Home say something that Alexa picks up.

But I have my Home TTS set in a language the Alexa doesn't understand. Think you make it possible to specify the language as a parameter instead/in addition to the config file?

**Comment by biofects** [comment]
I can add the lang to be passed and if not set it will use config. If neither are set it will default to en. Will that work?

**Comment by quack3d** [comment]
Great idea. That will work for me. :)

**Comment by biofects** [comment]
I have made the change, please test and let me know
`curl -d '{"text":"Hello, Lee. Have a nice day","ipaddress":"192.168.1.26","token":"JDJ887JJ***"}' -H "Content-Type: application/json" -X POST http://192.168.1.113:8092/google-home-messages/`

**Comment by quack3d** [comment]
Thanks a bunch. Worked like a charm.

**Comment by biofects** [comment]
Great! If you need anything else let me know.
