### ISSUE TITLE
Get key failed from Google

### ISSUE THREAD

**Issue by quack3d** [biofects/Google-Home-Messages#6]
Suddenly stopped working with the following error:

`Error: get key failed from google
    at C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\google-tts-api\lib\key.js:27:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by quack3d** [comment]
The google-tts package needs to be fixed.  The commit is here:

https://github.com/zlargon/google-tts/pull/14/commits/b5d1b8561fc1a34fac1e66bb280cd153d1a31044

Works fine after that change.

**Comment by biofects** [comment]
Sorry I am out of the country, I will try to get this in ASAP, Thank you!!!

**Comment by biofects** [comment]
I have made the update to google-tts-api\lib\key.js, can you confirm if this patch is what is needed to resolve it.

**Comment by quack3d** [comment]
Yeah, I made the same change myself. It's working fine now.

**Comment by biofects** [comment]
thanks again for the update.
