### ISSUE TITLE
Get key failed from Google again

### ISSUE THREAD

**Issue by quack3d** [biofects/Google-Home-Messages#7]
Get key failed from Google again. 

Error: get key failed from google at /home/pi/Google-Home-Messages/node_modules/google-tts-api/lib/key.js:23:23
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by quack3d** [comment]
Solved it by replacing key.js with this:

https://github.com/zlargon/google-tts/blob/a0f6ffaf9fd0f5f5dd544f3a226e784687dc92fc/lib/key.js

**Comment by biofects** [comment]
Thank you for jumping on this!!! @sepodele again you rocked this before I even had a chance to look. I have made the change in the master branch.
